# Generated by Django 5.2 on 2025-08-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category_expense_user_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10),
        ),
    ]
